services:
  - type: web
    name: segmaf-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120 --workers 1
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://segmaf.com.br
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_TOKEN
        sync: false
